application:
 version: 0.0.1
 title: oss

server:
  servlet:
    context-path: /oss

spring:
  profiles:
    active: local

--- # local
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    platform: h2
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      format_sql: true
      use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9090

logging:
  level:
    root: info
    org.hibernate.SQL: debug
